export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";
export const GET_POST_RESET = "GET_POST_RESET";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_RESET = "CREATE_POST_RESET";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";
export const UPDATE_POST_RESET = "UPDATE_POST_RESET";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";
export const LIKE_POST_RESET = "LIKE_POST_RESET";

export const DISLIKE_POST_REQUEST = "DISLIKE_POST_REQUEST";
export const DISLIKE_POST_SUCCESS = "DISLIKE_POST_SUCCESS";
export const DISLIKE_POST_FAIL = "DISLIKE_POST_FAIL";
export const DISLIKE_POST_RESET = "DISLIKE_POST_RESET";

export const LIST_MY_POSTS_REQUEST = "LIST_MY_POSTS_REQUEST";
export const LIST_MY_POSTS_SUCCESS = "LIST_MY_POSTS_SUCCESS";
export const LIST_MY_POSTS_FAIL = "LIST_MY_POSTS_FAIL";
export const LIST_MY_POSTS_RESET = "LIST_MY_POSTS_RESET";

export const LIST_POST_LIKES_REQUEST = "LIST_POST_LIKES_REQUEST";
export const LIST_POST_LIKES_SUCCESS = "LIST_POST_LIKES_SUCCESS";
export const LIST_POST_LIKES_FAIL = "LIST_POST_LIKES_FAIL";
export const LIST_POST_LIKES_RESET = "LIST_POST_LIKES_RESET";

export const GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST";
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS";
export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL";
export const GET_POST_DETAILS_RESET = "GET_POST_DETAILS_RESET";
